const menuList = [
  {
    title:'首页',
    key:'/home',
    icon:'home',
    isPublic:true, // 公开的，不管什么用户都能看到该Itme
  },
  {
    title:'商品',
    key:'/pro',
    icon:'appstore',
    children:[{
      title:'品类管理',
      key:'/pro/category',
      icon:'unordered-list',
    },{
      title:'商品管理',
      key:'/pro/product',
      icon:'appstore',
    }]
  },{
    title:'角色管理',
    key:'/role',
    icon:'user'
  },{
    title:'用户管理',
    key:'/user',
    icon:'user'
  },{
    title:'图形图标',
    key:'/graph',
    icon:'line-chart',
    children:[{
      title:'柱状图',
      key:'/graph/bar',
      icon:'bar-chart',
    },{
      title:'折线图',
      key:'/graph/line',
      icon:'stock',
    },{
      title:'饼图',
      key:'/graph/pie',
      icon:'pie-chart',
    }]
  },{
    title:'Excel',
    key:'/excel',
    icon:'file-excel',
    children:[{
      title:'Excel导入',
      key:'/excel/in',
      icon:'file-excel',
    },{
      title:'Excel导出',
      key:'/excel/out',
      icon:'file-excel',
    },{
      title:'多级表头导出',
      key:'/excel/mulitout',
      icon:'file-excel',
    }]
  },{
    title:'常用组件',
    key:'/com',
    icon:'code',
    children:[{
      title:'安全校验',
      key:'/com/security',
      icon:'security-scan',
    },{
      title:'手写轮播',
      key:'/com/slider',
      icon:'sliders',
    },{
      title:'上传图片',
      key:'/com/upload-img',
      icon:'cloud-upload',
    }]
  },{
    title:'项目代码地址',
    key:'/code',
    icon:'line-chart',
  },{
    title:'引导指南',
    key:'/guide',
    icon:'notification',
  }
];
export default menuList;