const menuList = [
  {
    title:'首页',
    key:'/home',
    icon:'home',
    isPublic:true, // 公开的，不管什么用户都能看到该Itme
  },
  {
    title:'商品',
    key:'/pro',
    icon:'appstore',
    children:[{
      title:'品类管理',
      key:'/pro/category',
      icon:'unordered-list',
    },{
      title:'商品管理',
      key:'/pro/product',
      icon:'appstore',
    }]
  },{
    title:'角色管理',
    key:'/role',
    icon:'user'
  },{
    title:'用户管理',
    key:'/user',
    icon:'user'
  },{
    title:'图形图标',
    key:'/graph',
    icon:'line-chart',
    children:[{
      title:'柱状图',
      key:'/graph/bar',
      icon:'bar-chart',
    },{
      title:'折线图',
      key:'/graph/line',
      icon:'stock',
    },{
      title:'饼图',
      key:'/graph/pie',
      icon:'pie-chart',
    }]
  }
];
export default menuList;